version: "3.8"

services:
  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: builder
    container_name: pose-frontend-dev
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:3000/api}
    volumes:
      - ../src:/app/src
      - ../public:/app/public
      - ../.next:/app/.next
    command: npm run dev
    networks:
      - pose-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  pose-network:
    external: true

