---
# ServiceMonitor for NestJS Applications
# Tells Prometheus to scrape metrics from all microservices

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nestjs-applications
  namespace: pose-monitoring
  labels:
    app: nestjs-applications
    release: kube-prometheus-stack
spec:
  # Select services in pose-microservices namespace
  namespaceSelector:
    matchNames:
      - pose-microservices
  
  # Select all services with label app
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - gateway-api
          - auth-service
          - item-service
          - email-service
          - category-service
  
  # Scrape configuration
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      scheme: http
