apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nline-monitoring

resources:
  # Load Balancer Metrics
  - traefik-metrics.yaml
  
  # Database Metrics
  - redis-metrics.yaml
  
  # Application Metrics
  - application-metrics.yaml
  
  # (Optional) Nginx Ingress - only if using Nginx instead of Traefik
  # - ingress-metrics.yaml

commonLabels:
  app.kubernetes.io/part-of: monitoring

