# # Prometheus Stack Configuration
# # Optimized for 7.8GB RAM server with 2 days retention
# # Features:
# # - Node Exporter (full system metrics)
# # - Database query monitoring
# # - Load Balancer (Traefik) metrics
# # - Application metrics (NestJS services)
# # - Service health and request tracking


nameOverride: "kube-prometheus-stack"
fullnameOverride: "kube-prometheus-stack"

prometheus:
  enabled: true
  service:
    type: NodePort
    nodePort: 30090
  
  prometheusSpec:
    retention: 1d
    retentionSize: "5GB"
    
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 400m
        memory: 512Mi

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi

    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    scrapeInterval: 15s
    evaluationInterval: 30s

    externalLabels:
      cluster: "pose-cluster"
      environment: "prod"

    # Scrape NestJS Microservices
    additionalScrapeConfigs:
      # Gateway API (HTTP on port 3000)
      - job_name: 'nestjs-gateway'
        scrape_interval: 30s
        scrape_timeout: 10s
        metrics_path: '/metrics'
        static_configs:
          - targets: ['gateway-service.pose-microservices.svc.cluster.local:3000']
            labels:
              service: 'gateway-api'

      # Auth Service (Metrics on port 9101)
      - job_name: 'nestjs-auth'
        scrape_interval: 30s
        scrape_timeout: 10s
        metrics_path: '/metrics'
        static_configs:
          - targets: ['auth-service.pose-microservices.svc.cluster.local:9101']
            labels:
              service: 'auth-service'

      # Item Service (Metrics on port 9102)
      - job_name: 'nestjs-item'
        scrape_interval: 30s
        scrape_timeout: 10s
        metrics_path: '/metrics'
        static_configs:
          - targets: ['item-service.pose-microservices.svc.cluster.local:9102']
            labels:
              service: 'item-service'

      # Email Service (Metrics on port 9103)
      - job_name: 'nestjs-email'
        scrape_interval: 30s
        scrape_timeout: 10s
        metrics_path: '/metrics'
        static_configs:
          - targets: ['email-service.pose-microservices.svc.cluster.local:9103']
            labels:
              service: 'email-service'

      # Category Service (Metrics on port 9105)
      - job_name: 'nestjs-category'
        scrape_interval: 30s
        scrape_timeout: 10s
        metrics_path: '/metrics'
        static_configs:
          - targets: ['category-service.pose-microservices.svc.cluster.local:9105']
            labels:
              service: 'category-service'

grafana:
  enabled: true
  adminPassword: "admin123"
  defaultDashboardsTimezone: "Asia/Bangkok"

  grafana.ini:
    server:
      root_url: "%(protocol)s://%(domain)s:%(http_port)s/"
    date_formats:
      default_timezone: "Asia/Bangkok"
    analytics:
      reporting_enabled: false
      check_for_updates: false
  
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

  persistence:
    enabled: true
    storageClassName: local-path
    size: 2Gi

  initChownData:
    enabled: false

  sidecar:
    dashboards:
      enabled: true
      defaultDashboardsEnabled: true
    datasources:
      enabled: true
      defaultDatasourceEnabled: true

  service:
    type: NodePort
    nodePort: 30001
    port: 80

alertmanager:
  enabled: false

prometheus-node-exporter:
  enabled: true
  hostNetwork: false
  hostPID: true
  hostRootFsMount:
    enabled: true

  service:
    port: 9100
    targetPort: 9100
  
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 150m
      memory: 128Mi

  extraArgs:
    - --collector.filesystem.mount-points-exclude=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/.+)($|/)
    - --collector.filesystem.fs-types-exclude=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$
    - --collector.netclass.ignored-devices=^(veth.*|docker.*|br-.*|lo)$
    - --collector.netdev.device-exclude=^(veth.*|docker.*|br-.*)$
    - --collector.processes
    - --collector.systemd
    - --collector.tcpstat

  prometheus:
    monitor:
      enabled: true
      interval: 30s

kube-state-metrics:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

prometheusOperator:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

defaultRules:
  create: true
  rules:
    alertmanager: true
    general: true
    node: true
    prometheus: true
    kubernetesApps: true
    kubernetesResources: true
    kubernetesStorage: true
    network: true

kubeControllerManager:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
