---
# Prometheus Minimal - ไม่มี Grafana, ไม่มี Alertmanager
apiVersion: v1
kind: Namespace
metadata:
  name: pose-monitoring

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: pose-monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 60s  # ลด frequency
      evaluation_interval: 60s
    
    scrape_configs:
      # Scrape NestJS services
      - job_name: 'nestjs-services'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - pose-microservices
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_label_app]
            regex: (gateway-api|auth-service|item-service|email-service|category-service)
            action: keep
          - source_labels: [__meta_kubernetes_service_name]
            target_label: service
          - source_labels: [__meta_kubernetes_namespace]
            target_label: namespace

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: pose-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
      containers:
      - name: prometheus
        image: prom/prometheus:v2.45.0
        args:
          - '--config.file=/etc/prometheus/prometheus.yml'
          - '--storage.tsdb.path=/prometheus'
          - '--storage.tsdb.retention.time=3d'  # เก็บแค่ 3 วัน
          - '--web.enable-lifecycle'
        ports:
        - containerPort: 9090
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus
        - name: storage
          mountPath: /prometheus
      volumes:
      - name: config
        configMap:
          name: prometheus-config
      - name: storage
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: pose-monitoring
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30090

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: pose-monitoring

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: pose-monitoring

