# Lightweight Prometheus Stack for 8GB RAM Server
# Optimized: ใช้ RAM ~800MB (แทน 1.5-2GB)

nameOverride: "kube-prometheus-stack"
fullnameOverride: "kube-prometheus-stack"

prometheus:
  enabled: true
  service:
    type: NodePort
    nodePort: 30090
  
  prometheusSpec:
    retention: 12h  # ลดจาก 2 วัน
    retentionSize: "3GB"  # ลดจาก 10GB
    
    resources:
      requests:
        cpu: 50m  # ลดจาก 150m
        memory: 256Mi  # ลดจาก 512Mi
      limits:
        cpu: 300m  # ลดจาก 600m
        memory: 512Mi  # ลดจาก 1024Mi

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi  # ลดจาก 10Gi

    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    scrapeInterval: 30s  # ลดความถี่ (จาก 15s)
    evaluationInterval: 60s  # ลดความถี่ (จาก 30s)

    externalLabels:
      cluster: "pose-cluster"
      environment: "prod"

    # Scrape NestJS microservices only
    additionalScrapeConfigs:
      - job_name: 'nestjs-gateway'
        scrape_timeout: 30s
        metrics_path: '/metrics'
        static_configs:
          - targets: ['gateway-service.pose-microservices.svc.cluster.local:3000']
            labels:
              service: 'gateway-api'

      - job_name: 'nestjs-microservices'
        scrape_timeout: 30s
        metrics_path: '/metrics'
        static_configs:
          - targets:
            - 'auth-service.pose-microservices.svc.cluster.local:9101'
            - 'item-service.pose-microservices.svc.cluster.local:9102'
            - 'email-service.pose-microservices.svc.cluster.local:9103'
            - 'category-service.pose-microservices.svc.cluster.local:9105'

grafana:
  enabled: true
  adminPassword: "admin123"
  defaultDashboardsTimezone: "Asia/Bangkok"

  grafana.ini:
    server:
      root_url: "%(protocol)s://%(domain)s:%(http_port)s/"
    date_formats:
      default_timezone: "Asia/Bangkok"
    analytics:
      reporting_enabled: false
      check_for_updates: false
  
  resources:
    requests:
      cpu: 25m  # ลดจาก 50m
      memory: 64Mi  # ลดจาก 128Mi
    limits:
      cpu: 150m  # ลดจาก 300m
      memory: 192Mi  # ลดจาก 384Mi

  persistence:
    enabled: true
    storageClassName: local-path
    size: 2Gi  # ลดจาก 3Gi

  initChownData:
    enabled: false

  sidecar:
    dashboards:
      enabled: true
      defaultDashboardsEnabled: false  # ปิด default dashboards เพื่อประหยัด RAM
    datasources:
      enabled: true
      defaultDatasourceEnabled: true

  service:
    type: NodePort
    nodePort: 30001
    port: 80

alertmanager:
  enabled: false  # ปิดเพื่อประหยัด RAM (~100MB)

prometheus-node-exporter:
  enabled: true
  hostNetwork: false
  hostPID: true
  hostRootFsMount:
    enabled: true

  service:
    port: 9100
    targetPort: 9100
  
  resources:
    requests:
      cpu: 25m  # ลดจาก 50m
      memory: 32Mi  # ลดจาก 64Mi
    limits:
      cpu: 100m  # ลดจาก 150m
      memory: 64Mi  # ลดจาก 128Mi

  extraArgs:
    - --collector.filesystem.mount-points-exclude=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/.+)($|/)
    - --collector.filesystem.fs-types-exclude=^(autofs|binfmt_misc|bpf|cgroup2?|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|iso9660|mqueue|nsfs|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|selinuxfs|squashfs|sysfs|tracefs)$

  prometheus:
    monitor:
      enabled: true
      interval: 30s

kube-state-metrics:
  enabled: true
  resources:
    requests:
      cpu: 25m  # ลดจาก 50m
      memory: 32Mi  # ลดจาก 64Mi
    limits:
      cpu: 100m  # ลดจาก 200m
      memory: 64Mi  # ลดจาก 128Mi

prometheusOperator:
  enabled: true
  resources:
    requests:
      cpu: 25m  # ลดจาก 50m
      memory: 32Mi  # ลดจาก 64Mi
    limits:
      cpu: 100m  # ลดจาก 200m
      memory: 64Mi  # ลดจาก 128Mi

defaultRules:
  create: false  # ปิด alerting rules เพื่อประหยัด RAM

kubeControllerManager:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false

