---
# Prometheus Minimal - ไม่มี Grafana, ไม่มี Alertmanager
apiVersion: v1
kind: Namespace
metadata:
  name: pose-monitoring

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: pose-monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 60s  # ลด frequency
      evaluation_interval: 60s
      scrape_timeout: 30s  # เพิ่ม timeout
    
    scrape_configs:
      # Scrape Gateway API (HTTP on port 3000)
      - job_name: 'gateway-api'
        scrape_interval: 60s
        scrape_timeout: 30s
        static_configs:
          - targets: ['gateway-service.pose-microservices.svc.cluster.local:3000']
            labels:
              service: 'gateway-api'
      
      # Scrape Microservices (Metrics on 910x ports)
      - job_name: 'nestjs-microservices'
        scrape_interval: 60s
        scrape_timeout: 30s
        static_configs:
          - targets: 
            - 'auth-service.pose-microservices.svc.cluster.local:9101'
            - 'item-service.pose-microservices.svc.cluster.local:9102'
            - 'email-service.pose-microservices.svc.cluster.local:9103'
            - 'category-service.pose-microservices.svc.cluster.local:9105'
        relabel_configs:
          - source_labels: [__address__]
            regex: '([^:]+):.*'
            replacement: '${1}'
            target_label: service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: pose-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
      containers:
      - name: prometheus
        image: prom/prometheus:v2.45.0
        args:
          - '--config.file=/etc/prometheus/prometheus.yml'
          - '--storage.tsdb.path=/prometheus'
          - '--storage.tsdb.retention.time=3d'  # เก็บแค่ 3 วัน
          - '--web.enable-lifecycle'
        ports:
        - containerPort: 9090
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus
        - name: storage
          mountPath: /prometheus
      volumes:
      - name: config
        configMap:
          name: prometheus-config
      - name: storage
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: pose-monitoring
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30090

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: pose-monitoring

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: pose-monitoring

