---
# ServiceMonitor for Traefik metrics
# Note: Traefik metrics endpoint is built-in, no need for separate service
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: traefik
  namespace: nline-monitoring
  labels:
    release: kube-prometheus-stack
    app: traefik
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
  namespaceSelector:
    matchNames:
    - kube-system
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics

