apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-api
  namespace: pose-microservices
  labels:
    app: gateway-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-api
  template:
    metadata:
      labels:
        app: gateway-api
    spec:
      containers:
      - name: gateway-api
        image: backend-gateway-api:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: pose-config
              key: NODE_ENV
        - name: AUTH_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: pose-config
              key: AUTH_SERVICE_HOST
        - name: AUTH_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: pose-config
              key: AUTH_SERVICE_PORT
        - name: ITEM_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: pose-config
              key: ITEM_SERVICE_HOST
        - name: ITEM_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: pose-config
              key: ITEM_SERVICE_PORT
        - name: EMAIL_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: pose-config
              key: EMAIL_SERVICE_HOST
        - name: EMAIL_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: pose-config
              key: EMAIL_SERVICE_PORT
        - name: CATEGORY_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              name: pose-config
              key: CATEGORY_SERVICE_HOST
        - name: CATEGORY_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              name: pose-config
              key: CATEGORY_SERVICE_PORT
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: pose-secrets
              key: JWT_SECRET
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /api
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 5
        imagePullPolicy: IfNotPresent

