apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-service
  namespace: pose-microservices
  labels:
    app: item-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: item-service
  template:
    metadata:
      labels:
        app: item-service
    spec:
      containers:
      - name: item-service
        image: backend-item-service:latest
        ports:
        - containerPort: 3002
        - containerPort: 9102
          name: metrics
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: pose-config
              key: NODE_ENV
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: pose-secrets
              key: DATABASE_URL
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          tcpSocket:
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 3002
          initialDelaySeconds: 10
          periodSeconds: 5
        imagePullPolicy: Never  # Use local image

